import { ReactComponent as homeIcon } from '../Assets/Icons/Anbu.svg';
import { ReactComponent as dashboardIcon } from '../Assets/Icons/Frame 28.svg';
import { ReactComponent as projectIcon } from '../Assets/Icons/Frame 29.svg';
import { ReactComponent as chatIcon } from '../Assets/Icons/Frame 30.svg';
import { ReactComponent as notificationIcon } from '../Assets/Icons/Frame 31.svg';
import { ReactComponent as settingIcon } from '../Assets/Icons/Frame 32.svg';
import { ReactComponent as dashboardIconHover } from '../Assets/Icons/dashboard Hover.svg';
import { ReactComponent as dashboardIconActive } from '../Assets/Icons/dashboard Active.svg';

import { ReactComponent as chatinput1 } from '../Assets/Icons/Frame.svg';
import { ReactComponent as chatinput2 } from '../Assets/Icons/Frame-1.svg';
import { ReactComponent as chatinput3 } from '../Assets/Icons/Frame-2.svg';
import { ReactComponent as chatinput4 } from '../Assets/Icons/Frame-3.svg';
import { ReactComponent as chatinput5 } from '../Assets/Icons/Frame-4.svg';
import { ReactComponent as chatinput6 } from '../Assets/Icons/Frame-5.svg';
import { ReactComponent as chatinput7 } from '../Assets/Icons/Frame-6.svg';
import { ReactComponent as chatinput8 } from '../Assets/Icons/Frame 135.svg';
import { ReactComponent as chatinput9 } from '../Assets/Icons/Frame-8.svg';
import { ReactComponent as chatinput10 } from '../Assets/Icons/Frame-9.svg';
import { ReactComponent as chatinput11 } from '../Assets/Icons/Frame-10.svg';
import { ReactComponent as chatinput12 } from '../Assets/Icons/Frame-11.svg';
import { ReactComponent as chatinput13 } from '../Assets/Icons/Frame-12.svg';
import { ReactComponent as chatinputline } from '../Assets/Icons/Line 24.svg';
import { ReactComponent as chatinput14 } from '../Assets/Icons/Frame-7.svg';
import { ReactComponent as chatinput15 } from '../Assets/Icons/Tt.svg';
import { ReactComponent as smileIcon } from '../Assets/Icons/smile 1.svg';
import { ReactComponent as imageIcon } from '../Assets/Icons/image-01 1.svg';
import { ReactComponent as attachmentIcon } from '../Assets/Icons/attachment-02 1.svg';
import { ReactComponent as micIcon } from '../Assets/Icons/micphone.svg';
import { ReactComponent as sendIcon } from '../Assets/Icons/send-button.svg';
import { ReactComponent as audioCallIcon } from '../Assets/Icons/call 2.svg';
import { ReactComponent as videoCallIcon } from '../Assets/Icons/call 2 (1).svg';
import { ReactComponent as locationIcon } from '../Assets/Icons/location-01 1.svg';
import { ReactComponent as mailIcon } from '../Assets/Icons/mail-01 1.svg';
import { ReactComponent as fileIcon } from '../Assets/Icons/file-01 1.svg';
import { ReactComponent as searchIcon } from '../Assets/Icons/search.svg';
import { ReactComponent as downArrowIcon } from '../Assets/Icons/arrow down.svg';
import { ReactComponent as downloadIcon } from '../Assets/Icons/download-04 1.svg';
import { ReactComponent as linkIcon } from '../Assets/Icons/link-01 1.svg';
import { ReactComponent as lightModeIcon } from '../Assets/Icons/Frame 33.svg';
import { ReactComponent as arrowLeftSharpIcon } from '../Assets/Icons/arrow-left-sharp.svg';
import { ReactComponent as arrowRightSharpIcon } from '../Assets/Icons/arrow-right-sharp.svg';
import { ReactComponent as arrowRightIcon } from '../Assets/Icons/Arrow right.svg';
import { ReactComponent as arrowRightIconNew } from '../Assets/Icons/arrow-right-icon-new.svg';
import { ReactComponent as arrowDownIcon } from '../Assets/Icons/arrow down.svg';
import { ReactComponent as moreHorizontalIcon } from '../Assets/Icons/more-horizontal-icon.svg';
import { ReactComponent as plusIcon } from '../Assets/Icons/plus-sign.svg';
import { ReactComponent as folderSharpIcon } from '../Assets/Icons/folder-sharp.svg';
import { ReactComponent as folderIcon } from '../Assets/Icons/folder.svg';
import { ReactComponent as addMemberIcon } from '../Assets/Icons/user-add-02 1.svg';
import { ReactComponent as circleIcon } from '../Assets/Icons/circle 3.svg';
import { ReactComponent as arrowUpDownIcon } from '../Assets/Icons/arrow-up-down.svg';
import { ReactComponent as flashIconOne } from '../Assets/Icons/flash-1.svg';
import { ReactComponent as flashIconTwo } from '../Assets/Icons/flash-2.svg';
import { ReactComponent as dragIcon } from '../Assets/Icons/Drag icon.svg';
import { ReactComponent as starCircleIcon } from '../Assets/Icons/star-circle.svg';
import { ReactComponent as flagIcon } from '../Assets/Icons/flag-icon.svg';
import { ReactComponent as timeIcon } from '../Assets/Icons/Time.svg';
import { ReactComponent as editIcon } from '../Assets/Icons/edit-icon.svg';
import { ReactComponent as tagIcon } from '../Assets/Icons/tag-icon.svg';
import { ReactComponent as subtaskIcon } from '../Assets/Icons/Sub task.svg';
import { ReactComponent as addUserIcon } from '../Assets/Icons/Add user.svg';
import { ReactComponent as loveIcon } from '../Assets/Icons/love-icon.svg';
import { ReactComponent as pentagonIcon } from '../Assets/Icons/pentagon.svg';
import { ReactComponent as IssueTypesIcon } from '../Assets/Icons/IssueTypes.svg';
import { ReactComponent as DeleteIcon } from '../Assets/Icons/DeleteIcon.svg';
import { ReactComponent as avatar1 } from '../Assets/Icons/avatar 1.svg';
import { ReactComponent as avatar2 } from '../Assets/Icons/avatar 2.svg';
import { ReactComponent as avatar3 } from '../Assets/Icons/avatar 3.svg';



export { chatinput1, chatinput2, chatinput3, chatinput4, chatinput5, chatinput6, chatinput7, chatinput8, chatinput9, chatinput10, chatinput11, chatinput12, chatinput13, chatinputline, chatinput14, chatinput15, smileIcon, imageIcon, attachmentIcon, micIcon, sendIcon, audioCallIcon, videoCallIcon, locationIcon, mailIcon, fileIcon, searchIcon, downArrowIcon, downloadIcon, linkIcon, homeIcon, dashboardIcon, projectIcon, chatIcon, notificationIcon, settingIcon, lightModeIcon, dashboardIconActive, dashboardIconHover, arrowLeftSharpIcon, arrowRightSharpIcon, arrowRightIcon, arrowDownIcon, moreHorizontalIcon, plusIcon, folderSharpIcon, addMemberIcon, circleIcon, arrowUpDownIcon, flashIconOne, flashIconTwo, dragIcon, starCircleIcon, flagIcon, timeIcon, editIcon, tagIcon, subtaskIcon, addUserIcon, arrowRightIconNew, folderIcon, loveIcon, pentagonIcon, IssueTypesIcon, DeleteIcon, avatar1, avatar2, avatar3 };